
import { Module } from './types';

export const TRANSLATIONS = {
  en: {
    heroTitle: "Empowering Every Tamil Student with AI",
    heroSubtitle: "Tamil Nadu’s Future Begins with AI.",
    heroBadge: "Learn. Leap. Lead.",
    getStarted: "Get Started",
    forSchools: "For Schools",
    dashboard: "Dashboard",
    modules: "Modules",
    progress: "Progress",
    continueLearning: "Continue Learning",
    completed: "Completed",
    pending: "Pending",
    submit: "Submit",
    schoolOnboarding: "School Onboarding",
    schoolName: "School Name",
    principalName: "Principal Name",
    register: "Register School",
    adminPanel: "Admin Panel",
    welcome: "Welcome",
    aiAssistant: "AI Assistant",
    askMe: "Ask me anything about this lesson...",
    assessment: "Assessment",
    switchLang: "Tamil",
    viewAs: "View as",
    chatWithUs: "Chat with Us",
    founders: "Founders",
    aboutUs: "About Us",
    helpCenter: "Help Center",
    pendingApprovals: "Pending Approvals",
    totalStudents: "Total Students",
    login: "Login",
    studentLogin: "Student Login",
    schoolLogin: "School Login",
    adminLogin: "Admin Login",
    logout: "Logout",
    phone: "Phone",
    email: "Email",
    board: "Board",
    stateBoard: "State Board",
    matriculation: "Matriculation",
    submitRequest: "Submit Request",
    aiToolsTitle: "Learn AI Tools — In Tamil",
    aiToolsDesc: "Master essential AI tools like Replit, Lovable, n8n, Runway through simple, Tamil-first lessons built for Tamil Nadu’s students.",
    nativeLangTitle: "Build Skills for Tamil Nadu’s Future",
    nativeLangDesc: "Gain job-ready abilities in coding, app development, web development, automation, and content creation to prepare for the state’s fast-growing tech ecosystem.",
    projectsTitle: "Transform Your Career in Tamil Nadu",
    projectsDesc: "Work on real-world projects, build your portfolio, and get internship-ready with learning paths designed to uplift students across Tamil Nadu.",
    footerRights: "All rights reserved.",
    footerMadeWith: "Made with ❤️ for Tamil Nadu.",
    grade: "Grade",
    streak: "Streak",
    days: "Days",
    keepLearning: "Keep learning to maintain your streak!",
    startLearning: "Start Learning",
    review: "Review",
    notes: "Notes",
    typeAnswer: "Type your answer here...",
    successfullySubmitted: "Successfully Submitted!",
    askAboutModule: "Ask about this module...",
    thinking: "Thinking...",
    schoolDashboard: "School Dashboard",
    registeredStudents: "Registered Students",
    modulesCompleted: "Modules Completed",
    pendingAssessments: "Pending Assessments",
    avgProgress: "Average Progress by Grade",
    topPerformers: "Top Performers",
    activeSchools: "Active Schools",
    onboardingQueue: "Onboarding Queue",
    approve: "Approve",
    active: "Active",
    medium: "Medium",
    noPending: "No pending requests",
    contact: "Contact",
    videoPlaceholder: "Video Player Placeholder",
    successMsg: "Registration Successful! We will contact you after approval.",
    aboutContent: [
      "Kalvi.AI is a Tamil Nadu based education platform built on a simple belief. Every student, from every district, deserves access to world class AI learning. We exist to remove the barriers that hold our youth back from the opportunities of tomorrow by making the future of technology understandable, practical and accessible in our own language.",
      "In a world where AI is reshaping every industry, many learners struggle with complex tools, English heavy content or expensive courses. Kalvi.AI changes this completely. We teach real AI skills such as coding, automation, app development, web creation and digital creativity in a way that any student in Tamil Nadu can learn, apply and grow with confidence.",
      "Our platform is Tamil first, student focused and fully outcome driven. Every lesson is crafted to be clear, practical and connected to real use cases. Whether you are a school student discovering AI for the first time, a college learner preparing for placements or a young creator building your first project, Kalvi.AI becomes your personal guide.",
      "We aim to shape the next generation of innovators, problem solvers and creators from Tamil Nadu. By empowering students with hands on skills and real world projects, we are not just teaching AI. We are building the foundation for a future where Tamil Nadu leads India in AI adoption.",
      "Kalvi.AI is more than a learning platform. It is a movement to uplift our state, our students and our future."
    ],
    // Quiz Translations
    quiz: "Practice Quiz",
    generateQuiz: "Generate Quiz",
    quizTitle: "AI Generated Quiz",
    nextQuestion: "Next Question",
    finishQuiz: "Finish Quiz",
    yourScore: "Your Score",
    correct: "Correct!",
    wrong: "Incorrect",
    quizLoading: "Generating questions...",
    quizExitWarning: "You have a quiz in progress. Are you sure you want to exit? Your progress will be lost.",
    // Offline / Sync Translations
    youAreOffline: "You are currently offline.",
    offlineMode: "Offline Mode",
    download: "Download",
    downloaded: "Downloaded",
    syncing: "Syncing your progress...",
    syncComplete: "Sync Complete!",
    savedOffline: "Saved offline. Will sync when online.",
    aiOffline: "AI Assistant is unavailable offline.",
    // Wizard Translations
    step1Title: "Institution Identity",
    step1Desc: "Tell us about your school.",
    step2Title: "Leadership",
    step2Desc: "Who is leading this initiative?",
    step3Title: "Capacity",
    step3Desc: "How many students will benefit?",
    next: "Next Step",
    back: "Back",
    finish: "Complete Registration",
    wizardSuccessTitle: "Welcome to the Future!",
    wizardSuccessDesc: "Your request has been submitted. Our team will verify your details and activate your dashboard shortly.",
    // Login Translations
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to continue to",
    studentRoleDesc: "Your learning journey continues here.",
    schoolRoleDesc: "Manage your institution and students.",
    adminRoleDesc: "Oversee the platform and growth.",
    username: "Username / Email",
    password: "Password",
    signIn: "Sign In",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    // Empty States
    noModulesTitle: "No modules found",
    noModulesDesc: "There are no modules available for this grade yet. Check back soon!",
    noNotificationsTitle: "All caught up!",
    noNotificationsDesc: "You have no new notifications at the moment.",
    // Legal
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    legalTitle: "Legal Information",
    lastUpdated: "Last Updated",
    // Help Center
    helpTitle: "How can we help you?",
    helpSubtitle: "Find answers to common questions about Kalvi.AI",
    faqCategories: {
      general: "General",
      students: "Students",
      schools: "Schools"
    },
    faqs: [
      { q: "How do I login?", a: "Click the 'Login' button at the top right. You can sign in as a Student or School Admin." },
      { q: "I forgot my password.", a: "Please contact your class teacher or school administrator to reset it." },
      { q: "Is this free for students?", a: "Yes, access is provided free of cost through partner schools." },
      { q: "Does it work on mobile?", a: "Yes, the platform is designed to work on all smartphones and tablets." },
    ],
    // New Features
    howItWorksTitle: "How It Works",
    howItWorksSub: "Start your AI journey in three simple steps.",
    step1Head: "Register Your School",
    step1Sub: "Schools apply for our AI program to provide native learning to their students.",
    step2Head: "Access Modules",
    step2Sub: "Students get personalized access to curriculum-aligned AI tools and lessons.",
    step3Head: "Build & Lead",
    step3Sub: "Apply skills in real-world projects and earn internship-ready certificates.",
    impactTitle: "Empowering Across Tamil Nadu",
    impactSub: "Our Reach and Impact",
    studentsImpacted: "Active Learners",
    districtsCovered: "Districts",
    modulesCompletedCount: "Modules Completed",
    projectsBuiltCount: "Projects Built",
    growthLabel: "MoM Growth",
    footerMission: "Kalvi.AI is committed to bringing world-class AI education to every student in Tamil Nadu, in our own language.",
    quickLinks: "Quick Links",
    legal: "Legal",
    connect: "Connect With Us",
    simplify: "Simplify",
    highlightHint: "Tip: Highlight any text to simplify it with AI.",
    listening: "Listening...",
    // Gamification & Sharing
    kalviCoins: "Kalvi Coins",
    leaderboard: "Leaderboard",
    topSchools: "Top Schools",
    sharePacket: "Share Packet",
    packetDownloaded: "Packet Downloaded!",
    packetShareDesc: "Share this file with friends via Bluetooth/ShareIt.",
    earnedCoins: "You earned",
    coins: "coins!",
    quizBonus: "Quiz Bonus"
  },
  ta: {
    heroTitle: "ஒவ்வொரு தமிழ் மாணவனையும் AI மூலம் மேம்படுத்துவோம்",
    heroSubtitle: "தமிழ்நாட்டின் எதிர்காலம் AI உடன் தொடங்குகிறது.",
    heroBadge: "கற்க. உயர. வழிநடத்த.",
    getStarted: "தொடங்கவும்",
    forSchools: "பள்ளிகளுக்கு",
    dashboard: "முகப்பு",
    modules: "பாடங்கள்",
    progress: "முன்னேற்றம்",
    continueLearning: "தொடர்ந்து கற்க",
    completed: "முடிக்கப்பட்டது",
    pending: "நிலுவையில் உள்ளது",
    submit: "சமர்ப்பிக்கவும்",
    schoolOnboarding: "பள்ளி பதிவு",
    schoolName: "பள்ளி பெயர்",
    principalName: "முதல்வர் பெயர்",
    register: "பதிவு செய்யவும்",
    adminPanel: "நிர்வாகக் குழு",
    welcome: "வணக்கம்",
    aiAssistant: "AI உதவியாளர்",
    askMe: "இப்பாடம் பற்றி எதுவேனும் கேட்கலாம்...",
    assessment: "மதிப்பீடு",
    switchLang: "English",
    viewAs: "பார்வை",
    chatWithUs: "எங்களுடன் பேசுங்கள்",
    founders: "நிறுவனர்கள்",
    aboutUs: "எங்களை பற்றி",
    helpCenter: "உதவி மையம்",
    pendingApprovals: "நிலுவையில் உள்ளவை",
    totalStudents: "மொத்த மாணவர்கள்",
    login: "உள்நுழை",
    studentLogin: "மாணவர் நுழைவு",
    schoolLogin: "பள்ளி நுழைவு",
    adminLogin: "நிர்வாக நுழைவு",
    logout: "வெளியேறு",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    board: "பாடத்திட்டம்",
    stateBoard: "மாநில பாடத்திட்டம்",
    matriculation: "மெட்ரிகுலேஷன்",
    submitRequest: "கோரிக்கையை சமர்ப்பிக்கவும்",
    aiToolsTitle: "AI கருவிகள் — தமிழில் கற்கவும்",
    aiToolsDesc: "Replit, Lovable, n8n, Runway போன்ற முக்கிய AI கருவிகளை, தமிழ் மாணவர்களுக்காக உருவாக்கப்பட்ட எளிய தமிழ் பாடங்கள் மூலம் கற்றுக்கொள்ளுங்கள்.",
    nativeLangTitle: "தமிழகத்தின் எதிர்காலத்திற்கான திறன்கள்",
    nativeLangDesc: "தமிழகத்தின் வளர்ந்து வரும் தொழில்நுட்பத் துறைக்குத் தயாராக, கோடிங், ஆப் உருவாக்கம் மற்றும் ஆட்டோமேஷன் திறன்களை வளர்த்துக் கொள்ளுங்கள்.",
    projectsTitle: "வேலைவாய்ப்பிற்கு தயாராகுங்கள்",
    projectsDesc: "நடைமுறைத் திட்டங்களை உருவாக்கி, உங்கள் போர்ட்ஃபோலியோவை மேம்படுத்தி, தமிழகம் முழுவதும் உள்ள மாணவர்களுக்கான வேலைவாய்ப்புகளுக்குத் தயாராகுங்கள்.",
    footerRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    footerMadeWith: "தமிழ்நாட்டிற்காக ❤️ உடன் உருவாக்கப்பட்டது.",
    grade: "வகுப்பு",
    streak: "தொடர் கற்றல்",
    days: "நாட்கள்",
    keepLearning: "உங்கள் கற்றலைத் தொடருங்கள்!",
    startLearning: "கற்கத் தொடங்கவும்",
    review: "மதிப்பாய்வு",
    notes: "குறிப்புகள்",
    typeAnswer: "உங்கள் விடையை இங்கே எழுதுங்கள்...",
    successfullySubmitted: "வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
    askAboutModule: "இப்பாடம் பற்றி கேளுங்கள்...",
    thinking: "யோசிக்கிறது...",
    schoolDashboard: "பள்ளி முகப்பு",
    registeredStudents: "பதிவு செய்த மாணவர்கள்",
    modulesCompleted: "முடிக்கப்பட்ட பாடங்கள்",
    pendingAssessments: "மதிப்பீடுகள் நிலுவை",
    avgProgress: "வகுப்பு வாரியாக சராசரி முன்னேற்றம்",
    topPerformers: "சிறந்த மாணவர்கள்",
    activeSchools: "செயலில் உள்ள பள்ளிகள்",
    onboardingQueue: "சேர்ப்பு வரிசை",
    approve: "ஒப்புதல்",
    active: "செயலில்",
    medium: "வழி",
    noPending: "நிலுவையில் உள்ள கோரிக்கைகள் இல்லை",
    contact: "தொடர்பு",
    videoPlaceholder: "வீடியோ இயக்கி இடம்",
    successMsg: "பதிவு வெற்றி! நிர்வாகி ஒப்புதலுக்குப் பிறகு தொடர்பு கொள்வோம்.",
    aboutContent: [
      "Kalvi.AI என்பது ஒரு எளிய நம்பிக்கையின் அடிப்படையில் உருவாக்கப்பட்ட தமிழ்நாட்டைச் சார்ந்த கல்வித் தளமாகும். ஒவ்வொரு மாவட்டத்திலிருந்தும் ஒவ்வொரு மாணவரும் உலகத்தரம் வாய்ந்த AI கற்றலைப் பெற தகுதியுடையவர்கள். நாளைய வாய்ப்புகளிலிருந்து நம் இளைஞர்களைத் தடுக்கும் தடைகளை நீக்கி, தொழில்நுட்பத்தின் எதிர்காலத்தை நம் சொந்த மொழியில் புரிந்துகொள்ளக்கூடியதாகவும், எளிதில் அணுகக்கூடியதாகவும் மாற்றுவதே எங்கள் நோக்கம்.",
      "AI ஒவ்வொரு துறையையும் மாற்றி அமைக்கும் உலகில், பல மாணவர்கள் சிக்கலான கருவிகள், ஆங்கிலம் நிறைந்த பாடங்கள் அல்லது அதிக கட்டணம் கொண்ட படிப்புகளால் சிரமப்படுகிறார்கள். Kalvi.AI இதை முற்றிலுமாக மாற்றுகிறது. கோடிங், ஆட்டோமேஷன், செயலி உருவாக்கம், வலைத்தள உருவாக்கம் மற்றும் டிஜிட்டல் படைப்பாற்றல் போன்ற உண்மையான AI திறன்களை தமிழ்நாட்டின் எந்தவொரு மாணவரும் நம்பிக்கையுடன் கற்கவும், பயன்படுத்தவும் வளரவும் கூடிய வகையில் நாங்கள் கற்பிக்கிறோம்.",
      "எங்கள் தளம் தமிழுக்கு முதலிடம், மாணவர் மையம் மற்றும் முழுமையான முடிவுகளை அடிப்படையாகக் கொண்டது. ஒவ்வொரு பாடமும் தெளிவாகவும், நடைமுறைக்கு உகந்ததாகவும், உண்மையான பயன்பாட்டுடன் இணைக்கப்பட்டதாகவும் வடிவமைக்கப்பட்டுள்ளது. நீங்கள் முதல்முறையாக AI ஐக் கண்டுபிடிக்கும் பள்ளி மாணவராக இருந்தாலும், வேலைவாய்ப்பிற்குத் தயாராகும் கல்லூரி மாணவராக இருந்தாலும் அல்லது உங்கள் முதல் திட்டத்தை உருவாக்கும் இளம் படைப்பாளவராக இருந்தாலும், Kalvi.AI உங்கள் தனிப்பட்ட வழிகாட்டியாக மாறுகிறது.",
      "தமிழ்நாட்டிலிருந்து அடுத்த தலைமுறை கண்டுபிடிப்பாளர்கள், சிக்கல் தீர்ப்பாளர்கள் மற்றும் படைப்பாளர்களை உருவாக்குவதே எங்கள் நோக்கம். நடைமுறைத் திறன்கள் மற்றும் உலகத் தரம் வாய்ந்த திட்டங்கள் மூலம் மாணவர்களை மேம்படுத்துவதன் மூலம், நாங்கள் AI ஐ மட்டும் கற்பிக்கவில்லை. AI ஏற்பில் தமிழ்நாடு இந்தியாவிலேயே முன்னணியில் இருக்கும் எதிர்காலத்திற்கான அடித்தளத்தை நாங்கள் அமைத்து வருகிறோம்.",
      "Kalvi.AI ஒரு கற்றல் தளம் மட்டுமல்ல. இது நம் மாநிலம், நம் மாணவர்கள் மற்றும் நம் எதிர்காலத்தை உயர்த்துவதற்கான ஒரு இயக்கம்."
    ],
    // Quiz Translations
    quiz: "பயிற்சி வினாடி வினா",
    generateQuiz: "வினாடி வினா உருவாக்கு",
    quizTitle: "AI வினாடி வினா",
    nextQuestion: "அடுத்த கேள்வி",
    finishQuiz: "முடிக்கவும்",
    yourScore: "உங்கள் மதிப்பெண்",
    correct: "சரியான பதில்!",
    wrong: "தவறான பதில்",
    quizLoading: "கேள்விகள் உருவாகின்றன...",
    quizExitWarning: "வினாடி வினா செயலில் உள்ளது. நீங்கள் வெளியேற விரும்புகிறீர்களா? உங்கள் முன்னேற்றம் இழக்கப்படும்.",
    // Offline / Sync Translations
    youAreOffline: "தற்போது இணைய இணைப்பு இல்லை.",
    offlineMode: "ஆஃப்லைன் முறை",
    download: "பதிவிறக்கு",
    downloaded: "பதிவிறக்கப்பட்டது",
    syncing: "ஒத்திசைக்கிறது...",
    syncComplete: "ஒத்திசைவு முடிந்தது!",
    savedOffline: "சேமிக்கப்பட்டது. இணையம் வந்ததும் சமர்ப்பிக்கப்படும்.",
    aiOffline: "இணையம் இல்லாமல் AI உதவியாளரை பயன்படுத்த முடியாது.",
    // Wizard Translations
    step1Title: "பள்ளி விவரங்கள்",
    step1Desc: "உங்கள் பள்ளியைப் பற்றி கூறுங்கள்.",
    step2Title: "தலைமைத்துவம்",
    step2Desc: "இந்த முயற்சியை யார் வழிநடத்துவது?",
    step3Title: "கொள்ளளவு",
    step3Desc: "எத்தனை மாணவர்கள் பயனடைவார்கள்?",
    next: "அடுத்தது",
    back: "பின்செல்க",
    finish: "பதிவை முடிக்கவும்",
    wizardSuccessTitle: "எதிர்காலத்திற்கு வருக!",
    wizardSuccessDesc: "உங்கள் கோரிக்கை சமர்ப்பிக்கப்பட்டது. எங்கள் குழு விரைவில் உங்கள் விவரங்களை சரிபார்த்து உங்களை தொடர்புகொள்ளும்.",
    // Login Translations
    welcomeBack: "மீண்டும் வருக",
    signInToContinue: "தொடர உள்நுழையவும்",
    studentRoleDesc: "உங்கள் கற்றல் பயணம் இங்கே தொடர்கிறது.",
    schoolRoleDesc: "உங்கள் பள்ளி மற்றும் மாணவர்களை நிர்வகிக்கவும்.",
    adminRoleDesc: "தள மேலாண்மை மற்றும் வளர்ச்சி.",
    username: "பயனர் பெயர் / மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழை",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    noAccount: "கணக்கு இல்லையா?",
    // Empty States
    noModulesTitle: "பாடங்கள் எதுவும் இல்லை",
    noModulesDesc: "இந்த வகுப்பிற்கான பாடங்கள் தற்போது இல்லை. விரைவில் மீண்டும் பார்க்கவும்!",
    noNotificationsTitle: "அறிவிப்புகள் இல்லை",
    noNotificationsDesc: "தற்போது உங்களுக்கு புதிய அறிவிப்புகள் எதுவும் இல்லை.",
    // Legal
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    termsOfService: "சேவை விதிமுறைகள்",
    legalTitle: "சட்டத் தகவல்கள்",
    lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது",
    // Help Center
    helpTitle: "நாங்கள் எப்படி உதவ முடியும்?",
    helpSubtitle: "Kalvi.AI பற்றிய பொதுவான கேள்விகளுக்கான பதில்களைக் கண்டறியவும்",
    faqCategories: {
      general: "பொதுவானவை",
      students: "மாணவர்கள்",
      schools: "பள்ளிகள்"
    },
    faqs: [
      { q: "நான் எப்படி உள்நுழைவது?", a: "'Login' பொத்தானை அழுத்தவும். மாணவர் அல்லது பள்ளி நிர்வாகியாக உள்நுழையலாம்." },
      { q: "கடவுச்சொல் மறந்துவிட்டது.", a: "உங்கள் வகுப்பு ஆசிரியர் அல்லது பள்ளி நிர்வாகியைத் தொடர்பு கொள்ளவும்." },
      { q: "மாணவர்களுக்கு இது இலவசமா?", a: "ஆம், பள்ளிகள் மூலம் வழங்கப்படும் அணுகல் முற்றிலும் இலவசம்." },
      { q: "மொபைலில் வேலை செய்யுமா?", a: "ஆம், அனைத்து ஸ்மார்ட்போன்களிலும் இது சிறப்பாக செயல்படும்." },
    ],
    // New Features
    howItWorksTitle: "இது எப்படி இயங்குகிறது?",
    howItWorksSub: "உங்கள் AI பயணத்தை மூன்று எளிய படிகளில் தொடங்குங்கள்.",
    step1Head: "உங்கள் பள்ளியைப் பதிவு செய்யுங்கள்",
    step1Sub: "தங்கள் மாணவர்களுக்கு நவீன AI கல்வியை வழங்க பள்ளிகள் பதிவு செய்கின்றன.",
    step2Head: "பாடங்களை அணுகவும்",
    step2Sub: "மாணவர்கள் தங்களுக்கென ஒதுக்கப்பட்ட AI பாடங்கள் மற்றும் கருவிகளை அணுகலாம்.",
    step3Head: "உருவாக்கி வழிநடத்துங்கள்",
    step3Sub: "நிஜ உலகத் திட்டங்களை உருவாக்கி, வேலைவாய்ப்பிற்குத் தேவையான சான்றிதழ்களைப் பெறுங்கள்.",
    impactTitle: "தமிழகம் முழுவதும் எங்களின் பயணம்",
    impactSub: "எங்களின் தாக்கம் மற்றும் வளர்ச்சி",
    studentsImpacted: "கற்கும் மாணவர்கள்",
    districtsCovered: "மாவட்டங்கள்",
    modulesCompletedCount: "முடிக்கப்பட்ட பாடங்கள்",
    projectsBuiltCount: "உருவாக்கப்பட்ட திட்டங்கள்",
    growthLabel: "மாதாந்திர வளர்ச்சி",
    footerMission: "தமிழகத்தின் ஒவ்வொரு மாணவருக்கும் உலகத்தரம் வாய்ந்த AI கல்வியை நம் தாய்மொழியில் வழங்குவதில் Kalvi.AI உறுதியாக உள்ளது.",
    quickLinks: "முக்கிய இணைப்புகள்",
    legal: "சட்ட விதிகூறு",
    connect: "எங்களை தொடர்பு கொள்ள",
    simplify: "எளிமையாக்கு",
    highlightHint: "குறிப்பு: AI மூலம் எளிமைப்படுத்த எந்த உரையையும் தேர்ந்தெடுக்கவும்.",
    listening: "கேட்கிறது...",
    // Gamification & Sharing
    kalviCoins: "Kalvi நாணயங்கள்",
    leaderboard: "முன்னணி பட்டியல்",
    topSchools: "சிறந்த பள்ளிகள்",
    sharePacket: "பகிரவும்",
    packetDownloaded: "பதிவிறக்கப்பட்டது!",
    packetShareDesc: "புளூடூத் அல்லது ஷேர்இட் மூலம் நண்பர்களுடன் பகிரவும்.",
    earnedCoins: "நீங்கள் வென்றது",
    coins: "நாணயங்கள்!",
    quizBonus: "வினாடி வினா போனஸ்"
  }
};

export const MODULES_6_8: Module[] = [
  {
    id: 'm68-1',
    title: { en: "Intro to AI", ta: "AI அறிமுகம்" },
    description: { en: "What is AI, what AI can and cannot do.", ta: "AI என்றால் என்ன, அதால் என்ன செய்ய முடியும்?" },
    content: { en: "Artificial Intelligence is the simulation of human intelligence processes by machines...", ta: "செயற்கை நுண்ணறிவு என்பது இயந்திரங்களால் மனித நுண்ணறிவு செயல்முறைகளின் உருவகப்படுத்துதலாகும்..." },
    assessmentTask: { en: "Use AI to create a simple story script of your choice with images.", ta: "AI ஐப் பயன்படுத்தி படங்களுடன் ஒரு எளிய கதை ஸ்கிரிப்டை உருவாக்கவும்." }
  },
  {
    id: 'm68-2',
    title: { en: "AI for Homework", ta: "வீட்டுப்பாடத்திற்கு AI" },
    description: { en: "Summarise lessons, create study plans.", ta: "பாடங்களை சுருக்கவும், படிப்பு திட்டங்களை உருவாக்கவும்." },
    content: { en: "Learn how to use Gemini to summarise long texts...", ta: "நீண்ட உரைகளை சுருக்க ஜெமினியை எவ்வாறு பயன்படுத்துவது என்று கற்றுக்கொள்ளுங்கள்..." },
    assessmentTask: { en: "Generate a study note for your science chapter.", ta: "உங்கள் அறிவியல் பாடத்திற்கு ஒரு குறிப்பை உருவாக்கவும்." }
  },
  {
    id: 'm68-3',
    title: { en: "AI for Presentations", ta: "விளக்கக்காட்சிகளுக்கு AI" },
    description: { en: "Create slides using AI.", ta: "AI ஐப் பயன்படுத்தி ஸ்லைடுகளை உருவாக்கவும்." },
    content: { en: "Tools like Gamma and Canva can generate slides...", ta: "காமா மற்றும் கேன்வா போன்ற கருவிகள் ஸ்லைடுகளை உருவாக்க முடியும்..." },
    assessmentTask: { en: "Create a 3-slide AI presentation on a topic.", ta: "ஒரு தலைப்பில் 3-ஸலைடு AI விளக்கக்காட்சியை உருவாக்கவும்." }
  },
  {
    id: 'm68-4',
    title: { en: "Digital Safety", ta: "டிஜிட்டல் பாதுகாப்பு" },
    description: { en: "Safe browsing, ethics of AI.", ta: "பாதுகாப்பான இணைய பயன்பாடு, AI நெறிமுறைகள்." },
    content: { en: "Always verify AI generated content...", ta: "AI உருவாக்கிய உள்ளடக்கத்தை எப்போதும் சரிபார்க்கவும்..." },
    assessmentTask: { en: "List 5 rules for safe AI usage.", ta: "பாதுகாப்பான AI பயன்பாட்டிற்கான 5 விதிகளைப் பட்டியலிடுங்கள்." }
  }
];

export const MODULES_9_12: Module[] = [
  {
    id: 'm912-1',
    title: { en: "AI for Web Design", ta: "வலை வடிவமைப்புக்கு AI" },
    description: { en: "Create landing pages and portfolios.", ta: "லேண்டிங் பக்கங்கள் மற்றும் போர்ட்ஃபோலியோக்களை உருவாக்கவும்." },
    content: { en: "Using AI to generate HTML/CSS layouts...", ta: "HTML/CSS தளவமைப்புகளை உருவாக்க AI ஐப் பயன்படுத்துதல்..." },
    assessmentTask: { en: "Create a personal portfolio website.", ta: "தனிப்பட்ட போர்ட்ஃபோலியோ வலைத்தளத்தை உருவாக்கவும்." }
  },
  {
    id: 'm912-2',
    title: { en: "No-Code App Building", ta: "நிரலாக்கமில்லா செயலி உருவாக்கம்" },
    description: { en: "Design & prototype no-code apps.", ta: "நோ-கோட் செயலிகளை வடிவமைக்கவும்." },
    content: { en: "Introduction to Glide and Bubble...", ta: "கிளைட் மற்றும் பபிள் அறிமுகம்..." },
    assessmentTask: { en: "Build a school attendance app.", ta: "பள்ளி வருகை செயலியை உருவாக்கவும்." }
  },
  {
    id: 'm912-3',
    title: { en: "AI for Coding", ta: "நிரலாக்கத்திற்கு AI" },
    description: { en: "Basics of programming and AI-assisted coding.", ta: "நிரலாக்கத்தின் அடிப்படைகள் மற்றும் AI-உதவி குறியீையாக்கம்." },
    content: { en: "How to use AI to debug and write Python scripts...", ta: "பைதான் ஸ்கிரிப்ட்களை எழுதவும் பிழைத்திருத்தவும் AI ஐ எவ்வாறு பயன்படுத்துவது..." },
    assessmentTask: { en: "Build a supermarket billing system using Python.", ta: "பைத்தானைப் பயன்படுத்தி பல்பொருள் அங்காடி பில்லிங் அமைப்பாை உருவாக்கவும்." }
  },
  {
    id: 'm912-4',
    title: { en: "Content Creation", ta: "உள்ளடக்க உருவாக்கம்" },
    description: { en: "Create posts, reels, voiceovers.", ta: "பதிவுகள், ரீல்கள், குரல்வழிகளை உருவாக்கவும்." },
    content: { en: "Using AI for video editing and script writing...", ta: "வீடியோ எடிட்டிங் மற்றும் ஸ்கிரிப்ட் எழுதுவதற்கு AI ஐப் பயன்படுத்துதல்..." },
    assessmentTask: { en: "Create a post and a short promotional video.", ta: "ஒரு பதிவு மற்றும் குறுகிய விளம்பர வீடியோவை உருவாக்கவும்." }
  }
];
